services:
  - type: web
    name: tienda
    env: docker
    plan: free
    branch: main
    healthCheckPath: /

    startCommand: >
      php artisan migrate --force &&
      php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4rstp15pdvs73bqibsg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: tienda_db_vkog
      - key: DB_USERNAME
        value: tienda_db_vkog_user
      - key: DB_PASSWORD
        sync: false
